testStrNil:
testStrEmpty: ""
testStr0: "0"
testStr1: "1"
testStr2: "2"

testBoolNil:
testBoolfalse: false
testBooltrue: true

testIntNil:
testInt0: 0
testInt1: 1
testInt2: 2

testFloatNil:
testFloat0p0: 0.0
testFloat0p1: 0.1
testFloat1p1: 1.1
testFloat2p1: 2.1

testMapNil:
testMap1:
  1: 1
testMap2:
  1: 1
  2: 1

testSliceNil:
testSliceEmpty: [ ]
testSlice1: [ 1 ]
testSlice2: [ 1,2 ]
testSlice2Str: [ "1", "2" ]