# GoFrame CLI tool configuration.
gfcli:
  gen:
    dao:
      - link: "mysql:root:12345678@tcp(127.0.0.1:3306)/gf_micro_user"
        tables: "user"
        removePrefix: ""
        descriptionTag: true
        noModelComment: true

    pbentity:
      - link: "mysql:root:12345678@tcp(127.0.0.1:3306)/gf_micro_user"
        tables: "user"