# GRPC Server.
grpc:
  address: ""
  name: "blog"
  logPath: ""
  logStdout: true
  errorStack: true
  errorLogEnabled: true
  errorLogPattern: "error-{Ymd}.log"
  accessLogEnabled: true
  accessLogPattern: "access-{Ymd}.log"

# Global logging.
logger:
  level: "info"
  stdout: true

# Database.
database:
  logger:
    level: "info"
    stdout: true

  default:
    link: "mysql:root:12345678@tcp(127.0.0.1:3306)/gf_micro_blog"
    debug: true

# 链路追踪
otlp:
  endpoint: "ip:port"
  traceToken: "token"