// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/yiqiang3344/gf-micro/example/blog/internal/dao/internal"
)

// internalStatsDao is internal type for wrapping internal DAO implements.
type internalStatsDao = *internal.StatsDao

// statsDao is the data access object for table stats.
// You can define custom methods on it to extend its functionality as you wish.
type statsDao struct {
	internalStatsDao
}

var (
	// Stats is globally public accessible object for table stats operations.
	Stats = statsDao{
		internal.NewStatsDao(),
	}
)

// Fill with you ideas below.
